#+TITLE: Ear Training Manual - Learning the Method
#+AUTHOR: Daniel Hones

* Introduction
** What is ear training?
   Ear training is the process of learning to identify the sounds you hear in music.  As you might imagine,
   this is a broad definition and ear training itself covers many topics within it.  For example, you can practice
   ear training to learn the sounds of individual chords, or to identify rhythms, or to recognize instruments
   by their timbre.  The particular method of ear training we will use with this program is called "functional ear
   training."  That's the process of learning to identify a note by its function within a key.  If that doesn't
   make sense to you right now, don't worry because we will cover everything you need to know in the upcoming sections.
** Why is it important?
   So now that you know what ear training is (if you didn't already), you would certainly be justified in asking,
   "Okay, so what?  I play pretty well, I have a decent ear, why do I need to ear train?"  The answer is, of course,
   that you don't /need/ to ear train.  You don't /need/ to eat healthy either, but it's a probably a good idea to
   try.  

   
** Perfect pitch
   Perfect pitch (or absolute pitch) is the ability to hear a note or notes and know instantly what pitches they
   are, without having to hear a reference pitch.  So far, all respectable research has concluded that a person has
   to be born with perfect pitch (or develop it by age 4?)  and it cannot be developed over time with training
   (((need citation))).  I don't have perfect pitch, and if you're reading this then you don't have perfect pitch
   either.  That's nothing to be ashamed of.  Only 1 in 10,000 people have the ability
   (((http://www.psychologytoday.com/articles/200607/the-mysteries-perfect-pitch))).  The only thing the rest of us
   can do is cry and come up with reasons why we're glad we aren't cursed with such an affliction.  And of course,
   we can ear train.

   While having perfect pitch would be very cool, probably the closest most of us can get is having very strong
   relative (or functional pitch).  We won't be able to tell precisely what notes we hear without a reference pitch
   to compare them to, but we can develop the ability to tell what notes we hear within the context of a key.
   More on that in a few sections.
** Reading music
   Despite the fact that regimented ear training often exists solely in the realm of music college classes, you do
   not need to be able to read music in order to ear train.  In fact, I've written this program and this document
   specifically to avoid written music.  This is simply because I believe in the value of ear training and I don't
   want to scare anybody off from the idea just because they don't read music.  There are many great musicians who
   can't read music and there are many great musicians who are excellent readers.  Personally, I can read music and
   I think that anyone who's serious about being a musician should learn to read.  But my goal here is not to
   proselytize so I'll leave it at that and we can move on.
** How this method is different

* Basics
** Overview
   This section will cover the just the basic knowledge you need in order to start using this method of ear
   training.  That includes the half steps and whole steps, the major scale, and the names of the notes within the
   major scale.  If you are confident in your knowledge of basic music theory you can probably skip this section.
   If there is anything unfamiliar to you in the rest of this document, refer back to this section to review.
** Pitches and notes
   Discuss naming conventions here, for example call X a note, what does bX or #X mean.  Discuss how pitches are
   categorized as one of 12 notes, octaves are a higher or lower "version" of the same pitch.
*** Whole steps and half steps
    The smallest interval that exists in Western (I don't mean country and western) music is the half step.  The
    next smallest interval is a whole step.  Two half steps, as you would expect and hope, do in fact make one whole
    step.  On certain instruments, it's possible to play pitches that are in between the 12 pitches we are used to
    hearing.  In this case, there are intervals smaller than a half step.  For our purposes, we don't need to be
    concerned with hearing pitches that are in between the 12 we know because they usually end up just sounding out
    of tune.  If you decide later on that you want to develop your ear for intonation or microtones (as the in
    between pitches are called), you can find other methods and tools to practice that.  In this program, everything
    is in tune.
*** The piano keyboard
    Most people have seen a piano keyboard.  If you haven't it looks like this:  (((Picture of piano keyboard)))

    A full-size piano has 88 keys and each plays a different pitch.  While that sounds overwhelming at first, we
    know that there are actually only 12 different notes in Western music.  And if you look closer at the piano, you
    can see that huge mess of white and black keys is actually just a pattern that repeats: (((Picture of one octave
    of keyboard C to B))).  In that pattern, there are 7 white keys and 5 black keys.  The white keys (if you start
    at the leftmost key) play what's called a major scale.  (((Sound clip of a C major scale))).  
** What is a key?
*** The major scale
    Use scale degrees.
*** The minor scale
** Solfege vs scale degrees
   In addition to scale degrees, there is another way to name the notes in a key (and even more beyond that but we
   won't worry about that).  It's called solfege, with a fancy accent over the first 'e' like this: solfège.  It
   also goes by the names solfeggio and sol-fa.  In my experience, solfège is the more common name, but to save me
   from having to remember how to type the accent, I'm going to call it solfege from here on out.  Solfege uses
   pronounceable syllables to name the notes instead of numbers.  It's very likely that you've already heard solfege
   syllables.  The song [[https://www.youtube.com/watch?v=xIjobdArtiA]["Do Re Mi Fa"]] from the "Sound of Music" is a famous example of using solfege syllables to
   sing the notes of a major scale.

   Before explaining what the syllables are and how they relate to the scale degrees we already know, let's take a
   moment to answer the question you probably have - "Why on Earth are there TWO different ways to name the notes in
   a major scale?  Is it to torture students and inexperienced musicians who don't know their theory?"  It's not
   there to torture you, although it might have that effect.  The main benefit of solfege is that it's easy to sing
   the syllables.  Just imagine Julie Andrews singing that song using scale degrees:
   #+BEGIN_EXAMPLE
   "1, a number that we start with.
   2, a number that comes after 1.
   3, the next number it's after 2.
   4 comes next, isn't this fun"
   #+END_EXAMPLE
   It's a little ridiculous, not to mention nowhere near as memorable.  For the purposes of this ear training
   method, you can decide whether you prefer scale degrees or solfege to name the notes, and just use that.  Here's
   how the solfege syllables relate to the notes in a major scale:

   | Scale degree |  1 |  2 |  3 |  4 |   5 |  6 |  7 |
   |--------------+----+----+----+----+-----+----+----|
   | Solfege      | Do | Re | Mi | Fa | Sol | La | Ti |

   Now for the pronunciation - "do" is pronounced like "dough", "re" is pronounced like "ray" (a drop of golden
   sun), and "mi" and "ti" sound like "me" and "tea" respectively.  This covers the diatonic notes in the major
   scale.  What about the in between notes?  In solfege, when a note is flatted, you take the first letter of the
   note and add "e" (sounds like "ay") as the vowel after it.  For example, ♭3 is "me" ("may") and ♭6 is "le"
   ("lay").  We need to make an exception for ♭2 and we call it "ra", as in "ra ra sis boom ba."  To alter the
   syllables for sharp notes, we take the first letter of the syllable and change the vowel sound to "i" ("ee").
   For example, ♯4 becomes "fi" and ♯6 becomes "li."  Therefore, just as ♯2 is the same note as ♭3, "ri" is the same
   note as "me."  They're enharmonic.  

   Here are the syllables formatted as diatonic and nondiatonic in both major and minor keys.  Just like we did with
   scale degrees, we'll only use the flat names for chromatic notes, to make it look a little cleaner and because
   our goal here isn't to be pedantic, but to have a working knowledge of the basics.  Of course, if you want to
   have a solid grasp of solfege, you should work on also using the enharmonic names.

   | Major        |    |    |    |    |    |    |    |     |    |    |    |    |
   |--------------+----+----+----+----+----+----+----+-----+----+----+----+----|
   | Non-diatonic |    | Ra |    | Me |    |    | Se |     | Le |    | Te |    |
   |--------------+----+----+----+----+----+----+----+-----+----+----+----+----|
   | Diatonic     | Do |    | Re |    | Mi | Fa |    | Sol |    | La |    | Ti |

   | Minor        |    |    |    |    |    |    |    |     |    |    |    |    |
   |--------------+----+----+----+----+----+----+----+-----+----+----+----+----|
   | Non-diatonic |    | Ra |    |    | Mi |    | Se |     |    | La |    | Ti |
   | Diatonic     | Do |    | Re | Me |    | Fa |    | Sol | Le |    | Te |    |


* How the method works
** The cadence
   A cadence is a sequence of chords that often occurs at the end of a phrase or section of a piece of music.  When
   it is used to conclude a piece of music, it usually has a sound of finality that clearly defines the key of the
   composition (for more about cadences, see this [[http://en.wikipedia.org/wiki/Cadence_(music)][Wikipedia page]]).  Here's an example of a cadence.  The first and
   last chords played are the tonic chord (or "home base") of the key: ((( Figure out how to play audio )))

   In this method of ear training, we'll play a sequence consisting of four chords to establish the sound of the
   key.  Then, we'll play one or more random notes simultaneously and learn to identify the function of each note in
   that particular key.
** Identifying the notes
   At first, trying to identify a note by listening for its function in a key is a daunting task.  How on Earth can
   you hear a cadence, then a note, and then just pluck out its name from thin air?  As with everything else, we
   start simply and progress in small increments.  The example below plays a cadence, and then plays Do (or scale
   degree 1) in the key:   ((( another sound example )))

   Play it several times and pay close attention to the way Do sounds.  To me it sounds stable and resolved, and
   truth be told, it sounds rather plain and uninteresting.  What does it sound like to you?  All the other notes
   sound less stable than Do. Often, it feels like your ear wants to hear them resolve to Do.  Listen to this next
   example, which plays the cadence followed by the note Re: ((( another sound example here )))

   To me, Re sounds like it has a healthy desire to move down a whole step to Do.  While it doesn't sound totally
   unstable or dissonant, there is a bit of tension there.  Go back and play the previous two samples several times
   and pay close attention to the difference in the way Do and Re sound.  Soon you will hear the difference between
   them as clearly as you can see the difference between orange and purple.

** Baby steps
   Now that you can identify Do and Re, it's time to start adding other notes.  That is the real benefit of using
   this program to practice this method of ear training.  You can customize which notes the program will choose from
   to play after the cadence, allowing you to progress in small easy increments or isolate notes that you have
   trouble with.  
** Different approaches

* Glossary
  (maybe format as a table)
  - cadence
  - chromatic
  - diatonic
  - enharmonic
  - half step: the smallest interval in Western music. 
  - interval: the distance between two pitches
  - key
  - major scale
  - minor scale
  - non-diatonic
  - pitch
  - scale degree
  - solfege
  - timbre
  - whole step: two half steps
